---
- name: Update Proxmox nodes
  hosts: proxmox
  become: yes
  tasks:
    - name: Set kernel_updated to False initially
      set_fact:
        kernel_updated: false
      when: ansible_facts is defined  # Ensures that the variable is always set

    - name: Get the current kernel version
      command: uname -r
      register: current_kernel
      changed_when: false  # This task doesn't change anything, it's just for info

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Perform dist-upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: apt_upgrade_result

    - name: Set kernel_updated to True if kernel upgraded
      set_fact:
        kernel_updated: true
      when: apt_upgrade_result.changed and current_kernel.stdout != ansible_kernel

    - name: Reboot if necessary (kernel upgrade)
      reboot:
        msg: "Rebooting after kernel upgrade"
        connect_timeout: 5
        reboot_timeout: 600
      when: kernel_updated
      notify: restart the server

  handlers:
    - name: restart the server
      reboot:
        msg: "Rebooting after kernel upgrade"
        connect_timeout: 5
        reboot_timeout: 600

